## **THƯ VIỆN**

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import math

## **ĐỌC DỮ LIỆU VÀ THÔNG TIN DỮ LIỆU**

### **Death_rate**

In [2]:
dr  = pd.read_csv('Data/Death_rate/672aab48-fb78-4c81-b26a-e15f6375e602_Data.csv', na_values=[".."]) 

dr.info()

dr.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271 entries, 0 to 270
Data columns (total 54 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Country Name   268 non-null    object
 1   Country Code   266 non-null    object
 2   Series Name    266 non-null    object
 3   Series Code    266 non-null    object
 4   1974 [YR1974]  256 non-null    float64
 5   1975 [YR1975]  256 non-null    float64
 6   1976 [YR1976]  256 non-null    float64
 7   1977 [YR1977]  257 non-null    float64
 8   1978 [YR1978]  257 non-null    float64
 9   1979 [YR1979]  257 non-null    float64
 10  1980 [YR1980]  257 non-null    float64
 11  1981 [YR1981]  256 non-null    float64
 12  1982 [YR1982]  256 non-null    float64
 13  1983 [YR1983]  256 non-null    float64
 14  1984 [YR1984]  257 non-null    float64
 15  1985 [YR1985]  257 non-null    float64
 16  1986 [YR1986]  257 non-null    float64
 17  1987 [YR1987]  257 non-null    float64
 18  1988 [YR1988]  257 non-null    float64
 19  1989 [YR1989]  258 non-null    float64
 20  1990 [YR1990]  260 non-null    float64
 21  1991 [YR1991]  260 non-null    float64
 22  1992 [YR1992]  260 non-null    float64
 23  1993 [YR1993]  260 non-null    float64
 24  1994 [YR1994]  260 non-null    float64
 25  1995 [YR1995]  260 non-null    float64
 26  1996 [YR1996]  260 non-null    float64
 27  1997 [YR1997]  259 non-null    float64
 28  1998 [YR1998]  259 non-null    float64
 29  1999 [YR1999]  259 non-null    float64
 30  2000 [YR2000]  260 non-null    float64
 31  2001 [YR2001]  260 non-null    float64
 32  2002 [YR2002]  260 non-null    float64
 33  2003 [YR2003]  260 non-null    float64
 34  2004 [YR2004]  263 non-null    float64
 35  2005 [YR2005]  262 non-null    float64
 36  2006 [YR2006]  263 non-null    float64
 37  2007 [YR2007]  262 non-null    float64
 38  2008 [YR2008]  262 non-null    float64
 39  2009 [YR2009]  262 non-null    float64
 40  2010 [YR2010]  262 non-null    float64
 41  2011 [YR2011]  261 non-null    float64
 42  2012 [YR2012]  262 non-null    float64
 43  2013 [YR2013]  261 non-null    float64
 44  2014 [YR2014]  263 non-null    float64
 45  2015 [YR2015]  262 non-null    float64
 46  2016 [YR2016]  263 non-null    float64
 47  2017 [YR2017]  262 non-null    float64
 48  2018 [YR2018]  263 non-null    float64
 49  2019 [YR2019]  263 non-null    float64
 50  2020 [YR2020]  262 non-null    float64
 51  2021 [YR2021]  261 non-null    float64
 52  2022 [YR2022]  263 non-null    float64
 53  2023 [YR2023]  0 non-null      float64
dtypes: float64(50), object(4)
memory usage: 114.5+ KB

,Country Name,Country Code,Series Name,Series Code,1974 [YR1974],1975 [YR1975],1976 [YR1976],1977 [YR1977],1978 [YR1978],1979 [YR1979],...,2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023]
0,Viet Nam,VNM,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,13.000,9.480,8.649,8.534,8.339,8.157,...,6.373,6.444,6.495,6.577,6.663,6.706,6.169,7.317,6.831,NaN
1,Afghanistan,AFG,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,24.773,24.241,23.718,23.179,23.875,24.797,...,7.395,7.331,7.077,7.027,6.981,6.791,7.113,7.344,6.906,NaN
2,Albania,ALB,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,7.417,7.137,6.937,6.711,6.595,6.445,...,7.868,7.947,8.035,8.150,8.308,8.480,10.785,11.325,11.194,NaN
3,Algeria,DZA,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,18.903,18.065,17.495,16.631,15.661,14.615,...,4.555,4.437,4.472,4.542,4.482,4.392,5.398,4.546,4.329,NaN
4,American Samoa,ASM,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.200,NaN,NaN,5.100,NaN,NaN,5.600,NaN,7.800,NaN

### **GDP**

In [3]:
gdp = pd.read_csv('Data/GDP/ec13fab8-31f0-4431-9c65-00bc500f44dc_Data.csv', na_values=[".."])

gdp.info()

gdp.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5325 entries, 0 to 5324
Data columns (total 54 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Country Name   5322 non-null   object
 1   Country Code   5320 non-null   object
 2   Series Name    5320 non-null   object
 3   Series Code    5320 non-null   object
 4   1974 [YR1974]  1846 non-null   float64
 5   1975 [YR1975]  1876 non-null   float64
 6   1976 [YR1976]  1887 non-null   float64
 7   1977 [YR1977]  1925 non-null   float64
 8   1978 [YR1978]  1931 non-null   float64
 9   1979 [YR1979]  1940 non-null   float64
 10  1980 [YR1980]  2028 non-null   float64
 11  1981 [YR1981]  2058 non-null   float64
 12  1982 [YR1982]  2076 non-null   float64
 13  1983 [YR1983]  2080 non-null   float64
 14  1984 [YR1984]  2102 non-null   float64
 15  1985 [YR1985]  2124 non-null   float64
 16  1986 [YR1986]  2135 non-null   float64
 17  1987 [YR1987]  2179 non-null   float64
 18  1988 [YR1988]  2202 non-null   float64
 19  1989 [YR1989]  2211 non-null   float64
 20  1990 [YR1990]  4095 non-null   float64
 21  1991 [YR1991]  4304 non-null   float64
 22  1992 [YR1992]  4318 non-null   float64
 23  1993 [YR1993]  4320 non-null   float64
 24  1994 [YR1994]  4336 non-null   float64
 25  1995 [YR1995]  4362 non-null   float64
 26  1996 [YR1996]  4364 non-null   float64
 27  1997 [YR1997]  4395 non-null   float64
 28  1998 [YR1998]  4403 non-null   float64
 29  1999 [YR1999]  4403 non-null   float64
 30  2000 [YR2000]  4444 non-null   float64
 31  2001 [YR2001]  4445 non-null   float64
 32  2002 [YR2002]  4494 non-null   float64
 33  2003 [YR2003]  4502 non-null   float64
 34  2004 [YR2004]  4568 non-null   float64
 35  2005 [YR2005]  4570 non-null   float64
 36  2006 [YR2006]  4585 non-null   float64
 37  2007 [YR2007]  4587 non-null   float64
 38  2008 [YR2008]  4558 non-null   float64
 39  2009 [YR2009]  4590 non-null   float64
 40  2010 [YR2010]  4587 non-null   float64
 41  2011 [YR2011]  4602 non-null   float64
 42  2012 [YR2012]  4582 non-null   float64
 43  2013 [YR2013]  4594 non-null   float64
 44  2014 [YR2014]  4590 non-null   float64
 45  2015 [YR2015]  4314 non-null   float64
 46  2016 [YR2016]  4215 non-null   float64
 47  2017 [YR2017]  4222 non-null   float64
 48  2018 [YR2018]  4224 non-null   float64
 49  2019 [YR2019]  4219 non-null   float64
 50  2020 [YR2020]  4214 non-null   float64
 51  2021 [YR2021]  4217 non-null   float64
 52  2022 [YR2022]  4177 non-null   float64
 53  2023 [YR2023]  3996 non-null   float64
dtypes: float64(50), object(4)
memory usage: 2.2+ MB

,Country Name,Country Code,Series Name,Series Code,1974 [YR1974],1975 [YR1975],1976 [YR1976],1977 [YR1977],1978 [YR1978],1979 [YR1979],...,2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023]
0,Viet Nam,VNM,GDP (constant 2015 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.236328e+11,2.392583e+11,2.552647e+11,2.729806e+11,2.933586e+11,3.149476e+11,3.239722e+11,3.322456e+11,3.592356e+11,3.773642e+11
1,Viet Nam,VNM,GDP (constant LCU),NY.GDP.MKTP.KN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.455392e+15,3.696826e+15,3.944144e+15,4.217875e+15,4.532739e+15,4.866316e+15,5.005756e+15,5.133589e+15,5.550617e+15,5.830725e+15
2,Viet Nam,VNM,GDP (current LCU),NY.GDP.MKTP.CN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.937032e+15,5.191324e+15,5.639401e+15,6.293905e+15,7.009042e+15,7.707200e+15,8.044386e+15,8.487476e+15,9.548738e+15,1.022181e+16
3,Viet Nam,VNM,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.334515e+11,2.392583e+11,2.570960e+11,2.813536e+11,3.101065e+11,3.343653e+11,3.466157e+11,3.664748e+11,4.103240e+11,4.297170e+11
4,Viet Nam,VNM,GDP deflator (base year varies by country),NY.GDP.DEFL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,1.428791e+02,1.404265e+02,1.429816e+02,1.492198e+02,1.546315e+02,1.583786e+02,1.607027e+02,1.653322e+02,1.720302e+02,1.753095e+02

### **Life_Expectancy**

In [4]:
life_exp = pd.read_csv('Data/Life_Expectancy/5564778c-2f63-4042-9e49-8ce9c9a3a87d_Data.csv', na_values=[".."]) 

life_exp.info()

life_exp.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 537 entries, 0 to 536
Data columns (total 68 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Country Name   534 non-null    object
 1   Country Code   532 non-null    object
 2   Series Name    532 non-null    object
 3   Series Code    532 non-null    object
 4   2023 [YR2023]  0 non-null      float64
 5   2022 [YR2022]  321 non-null    float64
 6   2021 [YR2021]  327 non-null    float64
 7   2020 [YR2020]  329 non-null    float64
 8   2019 [YR2019]  329 non-null    float64
 9   2018 [YR2018]  329 non-null    float64
 10  2017 [YR2017]  329 non-null    float64
 11  2016 [YR2016]  329 non-null    float64
 12  2015 [YR2015]  329 non-null    float64
 13  2014 [YR2014]  329 non-null    float64
 14  2013 [YR2013]  329 non-null    float64
 15  2012 [YR2012]  329 non-null    float64
 16  2011 [YR2011]  329 non-null    float64
 17  2010 [YR2010]  329 non-null    float64
 18  2009 [YR2009]  325 non-null    float64
 19  2008 [YR2008]  326 non-null    float64
 20  2007 [YR2007]  325 non-null    float64
 21  2006 [YR2006]  325 non-null    float64
 22  2005 [YR2005]  325 non-null    float64
 23  2004 [YR2004]  325 non-null    float64
 24  2003 [YR2003]  325 non-null    float64
 25  2002 [YR2002]  325 non-null    float64
 26  2001 [YR2001]  325 non-null    float64
 27  2000 [YR2000]  325 non-null    float64
 28  1999 [YR1999]  322 non-null    float64
 29  1998 [YR1998]  321 non-null    float64
 30  1997 [YR1997]  321 non-null    float64
 31  1996 [YR1996]  321 non-null    float64
 32  1995 [YR1995]  321 non-null    float64
 33  1994 [YR1994]  321 non-null    float64
 34  1993 [YR1993]  321 non-null    float64
 35  1992 [YR1992]  321 non-null    float64
 36  1991 [YR1991]  320 non-null    float64
 37  1990 [YR1990]  319 non-null    float64
 38  1989 [YR1989]  0 non-null      float64
 39  1988 [YR1988]  0 non-null      float64
 40  1987 [YR1987]  0 non-null      float64
 41  1986 [YR1986]  0 non-null      float64
 42  1985 [YR1985]  0 non-null      float64
 43  1984 [YR1984]  0 non-null      float64
 44  1983 [YR1983]  0 non-null      float64
 45  1982 [YR1982]  0 non-null      float64
 46  1981 [YR1981]  0 non-null      float64
 47  1980 [YR1980]  0 non-null      float64
 48  1979 [YR1979]  0 non-null      float64
 49  1978 [YR1978]  0 non-null      float64
 50  1977 [YR1977]  0 non-null      float64
 51  1976 [YR1976]  0 non-null      float64
 52  1975 [YR1975]  0 non-null      float64
 53  1974 [YR1974]  0 non-null      float64
 54  1973 [YR1973]  0 non-null      float64
 55  1972 [YR1972]  0 non-null      float64
 56  1971 [YR1971]  0 non-null      float64
 57  1970 [YR1970]  0 non-null      float64
 58  1969 [YR1969]  0 non-null      float64
 59  1968 [YR1968]  0 non-null      float64
 60  1967 [YR1967]  0 non-null      float64
 61  1966 [YR1966]  0 non-null      float64
 62  1965 [YR1965]  0 non-null      float64
 63  1964 [YR1964]  0 non-null      float64
 64  1963 [YR1963]  0 non-null      float64
 65  1962 [YR1962]  0 non-null      float64
 66  1961 [YR1961]  0 non-null      float64
 67  1960 [YR1960]  0 non-null      float64
dtypes: float64(64), object(4)
memory usage: 285.4+ KB

,Country Name,Country Code,Series Name,Series Code,2023 [YR2023],2022 [YR2022],2021 [YR2021],2020 [YR2020],2019 [YR2019],2018 [YR2018],...,1969 [YR1969],1968 [YR1968],1967 [YR1967],1966 [YR1966],1965 [YR1965],1964 [YR1964],1963 [YR1963],1962 [YR1962],1961 [YR1961],1960 [YR1960]
0,Afghanistan,AFG,Young people (ages 15-24) newly infected with HIV,SH.HIV.INCD.YG,NaN,500.000000,500.000000,500.000000,500.000000,500.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,Women's share of population ages 15+ living wi...,SH.DYN.AIDS.FE.ZS,NaN,29.313433,29.231041,29.152265,29.068788,28.995743,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Albania,ALB,Young people (ages 15-24) newly infected with HIV,SH.HIV.INCD.YG,NaN,100.000000,100.000000,100.000000,100.000000,100.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Albania,ALB,Women's share of population ages 15+ living wi...,SH.DYN.AIDS.FE.ZS,NaN,28.797251,28.561354,28.333333,28.113348,27.932099,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Algeria,DZA,Young people (ages 15-24) newly infected with HIV,SH.HIV.INCD.YG,NaN,500.000000,500.000000,500.000000,500.000000,500.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## **Tiền xử lý dữ liệu**

**Xử lý giá trị Null:** 

Nhận thấy một số lượng lớn dữ liệu bị thiếu nên em sẽ tiến hành kiểm tra phần trăm dữ liệu bị thiếu để tìm ra hướng xử lý như là xóa hết hay thay thế bằng giá trị trung bình, ...

In [ ]:
print(gdp.isnull().sum())

Country Name        3
Country Code        5
Series Name         5
Series Code         5
1974 [YR1974]    3479
1975 [YR1975]    3449
1976 [YR1976]    3438
1977 [YR1977]    3400
1978 [YR1978]    3394
1979 [YR1979]    3385
1980 [YR1980]    3297
1981 [YR1981]    3267
1982 [YR1982]    3249
1983 [YR1983]    3245
1984 [YR1984]    3223
1985 [YR1985]    3201
1986 [YR1986]    3190
1987 [YR1987]    3146
1988 [YR1988]    3123
1989 [YR1989]    3114
1990 [YR1990]    1230
1991 [YR1991]    1021
1992 [YR1992]    1007
1993 [YR1993]    1005
1994 [YR1994]     989
1995 [YR1995]     963
1996 [YR1996]     961
1997 [YR1997]     930
1998 [YR1998]     922
1999 [YR1999]     922
2000 [YR2000]     881
2001 [YR2001]     880
2002 [YR2002]     831
2003 [YR2003]     823
2004 [YR2004]     757
2005 [YR2005]     755
2006 [YR2006]     740
2007 [YR2007]     738
2008 [YR2008]     767
2009 [YR2009]     735
2010 [YR2010]     738
2011 [YR2011]     723
2012 [YR2012]     743
2013 [YR2013]     731
2014 [YR2014]     735
2015 [YR2015]    1011
2016 [YR2016]    1110
2017 [YR2017]    1103
2018 [YR2018]    1101
2019 [YR2019]    1106
2020 [YR2020]    1111
2021 [YR2021]    1108
2022 [YR2022]    1148
2023 [YR2023]    1329
dtype: int64

#### **Death_rate**

In [5]:
print(dr.isnull().sum())
print(dr.isnull().mean()*100)

Country Name       3
Country Code       5
Series Name        5
Series Code        5
1974 [YR1974]     15
1975 [YR1975]     15
1976 [YR1976]     15
1977 [YR1977]     14
1978 [YR1978]     14
1979 [YR1979]     14
1980 [YR1980]     14
1981 [YR1981]     15
1982 [YR1982]     15
1983 [YR1983]     15
1984 [YR1984]     14
1985 [YR1985]     14
1986 [YR1986]     14
1987 [YR1987]     14
1988 [YR1988]     14
1989 [YR1989]     13
1990 [YR1990]     11
1991 [YR1991]     11
1992 [YR1992]     11
1993 [YR1993]     11
1994 [YR1994]     11
1995 [YR1995]     11
1996 [YR1996]     11
1997 [YR1997]     12
1998 [YR1998]     12
1999 [YR1999]     12
2000 [YR2000]     11
2001 [YR2001]     11
2002 [YR2002]     11
2003 [YR2003]     11
2004 [YR2004]      8
2005 [YR2005]      9
2006 [YR2006]      8
2007 [YR2007]      9
2008 [YR2008]      9
2009 [YR2009]      9
2010 [YR2010]      9
2011 [YR2011]     10
2012 [YR2012]      9
2013 [YR2013]     10
2014 [YR2014]      8
2015 [YR2015]      9
2016 [YR2016]      8
2017 [YR2017]      9
2018 [YR2018]      8
2019 [YR2019]      8
2020 [YR2020]      9
2021 [YR2021]     10
2022 [YR2022]      8
2023 [YR2023]    271
dtype: int64
Country Name       1.107011
Country Code       1.845018
Series Name        1.845018
Series Code        1.845018
1974 [YR1974]      5.535055
1975 [YR1975]      5.535055
1976 [YR1976]      5.535055
1977 [YR1977]      5.166052
1978 [YR1978]      5.166052
1979 [YR1979]      5.166052
1980 [YR1980]      5.166052
1981 [YR1981]      5.535055
1982 [YR1982]      5.535055
1983 [YR1983]      5.535055
1984 [YR1984]      5.166052
1985 [YR1985]      5.166052
1986 [YR1986]      5.166052
1987 [YR1987]      5.166052
1988 [YR1988]      5.166052
1989 [YR1989]      4.797048
1990 [YR1990]      4.059041
1991 [YR1991]      4.059041
1992 [YR1992]      4.059041
1993 [YR1993]      4.059041
1994 [YR1994]      4.059041
1995 [YR1995]      4.059041
1996 [YR1996]      4.059041
1997 [YR1997]      4.428044
1998 [YR1998]      4.428044
1999 [YR1999]      4.428044
2000 [YR2000]      4.059041
2001 [YR2001]      4.059041
2002 [YR2002]      4.059041
2003 [YR2003]      4.059041
2004 [YR2004]      2.952030
2005 [YR2005]      3.321033
2006 [YR2006]      2.952030
2007 [YR2007]      3.321033
2008 [YR2008]      3.321033
2009 [YR2009]      3.321033
2010 [YR2010]      3.321033
2011 [YR2011]      3.690037
2012 [YR2012]      3.321033
2013 [YR2013]      3.690037
2014 [YR2014]      2.952030
2015 [YR2015]      3.321033
2016 [YR2016]      2.952030
2017 [YR2017]      3.321033
2018 [YR2018]      2.952030
2019 [YR2019]      2.952030
2020 [YR2020]      3.321033
2021 [YR2021]      3.690037
2022 [YR2022]      2.952030
2023 [YR2023]    100.000000
dtype: float64

In [6]:
dr["2023 [YR2023]"] = dr["2022 [YR2022]"]  # Sao chép giá trị năm 2022
dr.interpolate(method="linear", inplace=True)
dr.ffill(inplace=True)  # Điền dữ liệu còn thiếu từ trước
dr.bfill(inplace=True)  # Điền dữ liệu còn thiếu từ sau

C:\Users\ASUS\AppData\Local\Temp\ipykernel_22696\1364755925.py:2: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  dr.interpolate(method="linear", inplace=True)

In [7]:
print(dr.isnull().sum())

dr.head()

Country Name     0
Country Code     0
Series Name      0
Series Code      0
1974 [YR1974]    0
1975 [YR1975]    0
1976 [YR1976]    0
1977 [YR1977]    0
1978 [YR1978]    0
1979 [YR1979]    0
1980 [YR1980]    0
1981 [YR1981]    0
1982 [YR1982]    0
1983 [YR1983]    0
1984 [YR1984]    0
1985 [YR1985]    0
1986 [YR1986]    0
1987 [YR1987]    0
1988 [YR1988]    0
1989 [YR1989]    0
1990 [YR1990]    0
1991 [YR1991]    0
1992 [YR1992]    0
1993 [YR1993]    0
1994 [YR1994]    0
1995 [YR1995]    0
1996 [YR1996]    0
1997 [YR1997]    0
1998 [YR1998]    0
1999 [YR1999]    0
2000 [YR2000]    0
2001 [YR2001]    0
2002 [YR2002]    0
2003 [YR2003]    0
2004 [YR2004]    0
2005 [YR2005]    0
2006 [YR2006]    0
2007 [YR2007]    0
2008 [YR2008]    0
2009 [YR2009]    0
2010 [YR2010]    0
2011 [YR2011]    0
2012 [YR2012]    0
2013 [YR2013]    0
2014 [YR2014]    0
2015 [YR2015]    0
2016 [YR2016]    0
2017 [YR2017]    0
2018 [YR2018]    0
2019 [YR2019]    0
2020 [YR2020]    0
2021 [YR2021]    0
2022 [YR2022]    0
2023 [YR2023]    0
dtype: int64

,Country Name,Country Code,Series Name,Series Code,1974 [YR1974],1975 [YR1975],1976 [YR1976],1977 [YR1977],1978 [YR1978],1979 [YR1979],...,2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023]
0,Viet Nam,VNM,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,13.000000,9.480000,8.649000,8.534,8.339000,8.157000,...,6.373,6.444,6.495,6.577,6.663,6.706,6.169,7.317000,6.831,6.831
1,Afghanistan,AFG,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,24.773000,24.241000,23.718000,23.179,23.875000,24.797000,...,7.395,7.331,7.077,7.027,6.981,6.791,7.113,7.344000,6.906,6.906
2,Albania,ALB,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,7.417000,7.137000,6.937000,6.711,6.595000,6.445000,...,7.868,7.947,8.035,8.150,8.308,8.480,10.785,11.325000,11.194,11.194
3,Algeria,DZA,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,18.903000,18.065000,17.495000,16.631,15.661000,14.615000,...,4.555,4.437,4.472,4.542,4.482,4.392,5.398,4.546000,4.329,4.329
4,American Samoa,ASM,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,20.138667,19.671333,19.277333,18.611,17.849667,17.055333,...,4.200,5.900,4.386,5.100,4.441,4.146,5.600,5.700333,7.800,7.800

In [8]:
gdp.to_csv('processedByTam/processed_death_rate.csv', index=False)

#### **GDP**

In [9]:
print(gdp.isnull().sum())

Country Name        3
Country Code        5
Series Name         5
Series Code         5
1974 [YR1974]    3479
1975 [YR1975]    3449
1976 [YR1976]    3438
1977 [YR1977]    3400
1978 [YR1978]    3394
1979 [YR1979]    3385
1980 [YR1980]    3297
1981 [YR1981]    3267
1982 [YR1982]    3249
1983 [YR1983]    3245
1984 [YR1984]    3223
1985 [YR1985]    3201
1986 [YR1986]    3190
1987 [YR1987]    3146
1988 [YR1988]    3123
1989 [YR1989]    3114
1990 [YR1990]    1230
1991 [YR1991]    1021
1992 [YR1992]    1007
1993 [YR1993]    1005
1994 [YR1994]     989
1995 [YR1995]     963
1996 [YR1996]     961
1997 [YR1997]     930
1998 [YR1998]     922
1999 [YR1999]     922
2000 [YR2000]     881
2001 [YR2001]     880
2002 [YR2002]     831
2003 [YR2003]     823
2004 [YR2004]     757
2005 [YR2005]     755
2006 [YR2006]     740
2007 [YR2007]     738
2008 [YR2008]     767
2009 [YR2009]     735
2010 [YR2010]     738
2011 [YR2011]     723
2012 [YR2012]     743
2013 [YR2013]     731
2014 [YR2014]     735
2015 [YR2015]    1011
2016 [YR2016]    1110
2017 [YR2017]    1103
2018 [YR2018]    1101
2019 [YR2019]    1106
2020 [YR2020]    1111
2021 [YR2021]    1108
2022 [YR2022]    1148
2023 [YR2023]    1329
dtype: int64

In [10]:
# Chỉ lấy các cột có chứa dữ liệu theo năm
year_cols = [col for col in gdp.columns if "[YR" in col]

# Nội suy tuyến tính trên các cột này
gdp[year_cols] = gdp[year_cols].interpolate(method="linear", axis=1)

In [11]:
# Điền dữ liệu còn thiếu từ trước
gdp[year_cols] = gdp[year_cols].ffill(axis=1)
gdp[year_cols] = gdp[year_cols].bfill(axis=1)

In [12]:
# Xóa các dòng có tất cả giá trị còn thiếu
gdp = gdp.dropna(subset=year_cols, how="all")

In [13]:
print(gdp.isnull().sum())

Country Name     0
Country Code     0
Series Name      0
Series Code      0
1974 [YR1974]    0
1975 [YR1975]    0
1976 [YR1976]    0
1977 [YR1977]    0
1978 [YR1978]    0
1979 [YR1979]    0
1980 [YR1980]    0
1981 [YR1981]    0
1982 [YR1982]    0
1983 [YR1983]    0
1984 [YR1984]    0
1985 [YR1985]    0
1986 [YR1986]    0
1987 [YR1987]    0
1988 [YR1988]    0
1989 [YR1989]    0
1990 [YR1990]    0
1991 [YR1991]    0
1992 [YR1992]    0
1993 [YR1993]    0
1994 [YR1994]    0
1995 [YR1995]    0
1996 [YR1996]    0
1997 [YR1997]    0
1998 [YR1998]    0
1999 [YR1999]    0
2000 [YR2000]    0
2001 [YR2001]    0
2002 [YR2002]    0
2003 [YR2003]    0
2004 [YR2004]    0
2005 [YR2005]    0
2006 [YR2006]    0
2007 [YR2007]    0
2008 [YR2008]    0
2009 [YR2009]    0
2010 [YR2010]    0
2011 [YR2011]    0
2012 [YR2012]    0
2013 [YR2013]    0
2014 [YR2014]    0
2015 [YR2015]    0
2016 [YR2016]    0
2017 [YR2017]    0
2018 [YR2018]    0
2019 [YR2019]    0
2020 [YR2020]    0
2021 [YR2021]    0
2022 [YR2022]    0
2023 [YR2023]    0
dtype: int64

In [14]:
gdp.to_csv('processedByTam/processed_gdp.csv', index=False)

#### **Life_Expentancy**

In [15]:
print(life_exp.isnull().sum())
print(life_exp.shape)  # Kiểm tra kích thước dữ liệu

Country Name       3
Country Code       5
Series Name        5
Series Code        5
2023 [YR2023]    537
                ...
1964 [YR1964]    537
1963 [YR1963]    537
1962 [YR1962]    537
1961 [YR1961]    537
1960 [YR1960]    537
Length: 68, dtype: int64
(537, 68)

In [16]:
# Xóa các dòng mà tất cả giá trị trong cột năm đều NaN
life_exp = life_exp.dropna(subset=[col for col in life_exp.columns if "[YR" in col], how="all")

# Xóa các cột mà toàn bộ giá trị là NaN (nếu có)
life_exp.dropna(axis=1, how="all", inplace=True)

In [17]:
print(life_exp.isnull().sum())

Country Name      0
Country Code      0
Series Name       0
Series Code       0
2022 [YR2022]    14
2021 [YR2021]     8
2020 [YR2020]     6
2019 [YR2019]     6
2018 [YR2018]     6
2017 [YR2017]     6
2016 [YR2016]     6
2015 [YR2015]     6
2014 [YR2014]     6
2013 [YR2013]     6
2012 [YR2012]     6
2011 [YR2011]     6
2010 [YR2010]     6
2009 [YR2009]    10
2008 [YR2008]     9
2007 [YR2007]    10
2006 [YR2006]    10
2005 [YR2005]    10
2004 [YR2004]    10
2003 [YR2003]    10
2002 [YR2002]    10
2001 [YR2001]    10
2000 [YR2000]    10
1999 [YR1999]    13
1998 [YR1998]    14
1997 [YR1997]    14
1996 [YR1996]    14
1995 [YR1995]    14
1994 [YR1994]    14
1993 [YR1993]    14
1992 [YR1992]    14
1991 [YR1991]    15
1990 [YR1990]    16
dtype: int64

In [18]:
life_exp.to_csv('processedByTam/processed_life_exp.csv', index=False)