## **THƯ VIỆN**

In [21]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import math

## **ĐỌC DỮ LIỆU VÀ THÔNG TIN DỮ LIỆU**

### **Death_rate**

In [22]:
dr  = pd.read_csv('Data/Death_rate/672aab48-fb78-4c81-b26a-e15f6375e602_Data.csv', na_values=[".."]) 

dr.info()

dr.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271 entries, 0 to 270
Data columns (total 54 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Country Name   268 non-null    object
 1   Country Code   266 non-null    object
 2   Series Name    266 non-null    object
 3   Series Code    266 non-null    object
 4   1974 [YR1974]  256 non-null    float64
 5   1975 [YR1975]  256 non-null    float64
 6   1976 [YR1976]  256 non-null    float64
 7   1977 [YR1977]  257 non-null    float64
 8   1978 [YR1978]  257 non-null    float64
 9   1979 [YR1979]  257 non-null    float64
 10  1980 [YR1980]  257 non-null    float64
 11  1981 [YR1981]  256 non-null    float64
 12  1982 [YR1982]  256 non-null    float64
 13  1983 [YR1983]  256 non-null    float64
 14  1984 [YR1984]  257 non-null    float64
 15  1985 [YR1985]  257 non-null    float64
 16  1986 [YR1986]  257 non-null    float64
 17  1987 [YR1987]  257 non-null    float64
 18  1988 [YR1988]  257 non-null    float64
 19  1989 [YR1989]  258 non-null    float64
 20  1990 [YR1990]  260 non-null    float64
 21  1991 [YR1991]  260 non-null    float64
 22  1992 [YR1992]  260 non-null    float64
 23  1993 [YR1993]  260 non-null    float64
 24  1994 [YR1994]  260 non-null    float64
 25  1995 [YR1995]  260 non-null    float64
 26  1996 [YR1996]  260 non-null    float64
 27  1997 [YR1997]  259 non-null    float64
 28  1998 [YR1998]  259 non-null    float64
 29  1999 [YR1999]  259 non-null    float64
 30  2000 [YR2000]  260 non-null    float64
 31  2001 [YR2001]  260 non-null    float64
 32  2002 [YR2002]  260 non-null    float64
 33  2003 [YR2003]  260 non-null    float64
 34  2004 [YR2004]  263 non-null    float64
 35  2005 [YR2005]  262 non-null    float64
 36  2006 [YR2006]  263 non-null    float64
 37  2007 [YR2007]  262 non-null    float64
 38  2008 [YR2008]  262 non-null    float64
 39  2009 [YR2009]  262 non-null    float64
 40  2010 [YR2010]  262 non-null    float64
 41  2011 [YR2011]  261 non-null    float64
 42  2012 [YR2012]  262 non-null    float64
 43  2013 [YR2013]  261 non-null    float64
 44  2014 [YR2014]  263 non-null    float64
 45  2015 [YR2015]  262 non-null    float64
 46  2016 [YR2016]  263 non-null    float64
 47  2017 [YR2017]  262 non-null    float64
 48  2018 [YR2018]  263 non-null    float64
 49  2019 [YR2019]  263 non-null    float64
 50  2020 [YR2020]  262 non-null    float64
 51  2021 [YR2021]  261 non-null    float64
 52  2022 [YR2022]  263 non-null    float64
 53  2023 [YR2023]  0 non-null      float64
dtypes: float64(50), object(4)
memory usage: 114.5+ KB

,Country Name,Country Code,Series Name,Series Code,1974 [YR1974],1975 [YR1975],1976 [YR1976],1977 [YR1977],1978 [YR1978],1979 [YR1979],...,2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023]
0,Viet Nam,VNM,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,13.000,9.480,8.649,8.534,8.339,8.157,...,6.373,6.444,6.495,6.577,6.663,6.706,6.169,7.317,6.831,NaN
1,Afghanistan,AFG,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,24.773,24.241,23.718,23.179,23.875,24.797,...,7.395,7.331,7.077,7.027,6.981,6.791,7.113,7.344,6.906,NaN
2,Albania,ALB,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,7.417,7.137,6.937,6.711,6.595,6.445,...,7.868,7.947,8.035,8.150,8.308,8.480,10.785,11.325,11.194,NaN
3,Algeria,DZA,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,18.903,18.065,17.495,16.631,15.661,14.615,...,4.555,4.437,4.472,4.542,4.482,4.392,5.398,4.546,4.329,NaN
4,American Samoa,ASM,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.200,NaN,NaN,5.100,NaN,NaN,5.600,NaN,7.800,NaN

### **GDP**

In [23]:
gdp = pd.read_csv('Data/GDP/ec13fab8-31f0-4431-9c65-00bc500f44dc_Data.csv')

gdp.info()

gdp.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5325 entries, 0 to 5324
Data columns (total 54 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Country Name   5322 non-null   object
 1   Country Code   5320 non-null   object
 2   Series Name    5320 non-null   object
 3   Series Code    5320 non-null   object
 4   1974 [YR1974]  5320 non-null   object
 5   1975 [YR1975]  5320 non-null   object
 6   1976 [YR1976]  5320 non-null   object
 7   1977 [YR1977]  5320 non-null   object
 8   1978 [YR1978]  5320 non-null   object
 9   1979 [YR1979]  5320 non-null   object
 10  1980 [YR1980]  5320 non-null   object
 11  1981 [YR1981]  5320 non-null   object
 12  1982 [YR1982]  5320 non-null   object
 13  1983 [YR1983]  5320 non-null   object
 14  1984 [YR1984]  5320 non-null   object
 15  1985 [YR1985]  5320 non-null   object
 16  1986 [YR1986]  5320 non-null   object
 17  1987 [YR1987]  5320 non-null   object
 18  1988 [YR1988]  5320 non-null   object
 19  1989 [YR1989]  5320 non-null   object
 20  1990 [YR1990]  5320 non-null   object
 21  1991 [YR1991]  5320 non-null   object
 22  1992 [YR1992]  5320 non-null   object
 23  1993 [YR1993]  5320 non-null   object
 24  1994 [YR1994]  5320 non-null   object
 25  1995 [YR1995]  5320 non-null   object
 26  1996 [YR1996]  5320 non-null   object
 27  1997 [YR1997]  5320 non-null   object
 28  1998 [YR1998]  5320 non-null   object
 29  1999 [YR1999]  5320 non-null   object
 30  2000 [YR2000]  5320 non-null   object
 31  2001 [YR2001]  5320 non-null   object
 32  2002 [YR2002]  5320 non-null   object
 33  2003 [YR2003]  5320 non-null   object
 34  2004 [YR2004]  5320 non-null   object
 35  2005 [YR2005]  5320 non-null   object
 36  2006 [YR2006]  5320 non-null   object
 37  2007 [YR2007]  5320 non-null   object
 38  2008 [YR2008]  5320 non-null   object
 39  2009 [YR2009]  5320 non-null   object
 40  2010 [YR2010]  5320 non-null   object
 41  2011 [YR2011]  5320 non-null   object
 42  2012 [YR2012]  5320 non-null   object
 43  2013 [YR2013]  5320 non-null   object
 44  2014 [YR2014]  5320 non-null   object
 45  2015 [YR2015]  5320 non-null   object
 46  2016 [YR2016]  5320 non-null   object
 47  2017 [YR2017]  5320 non-null   object
 48  2018 [YR2018]  5320 non-null   object
 49  2019 [YR2019]  5320 non-null   object
 50  2020 [YR2020]  5320 non-null   object
 51  2021 [YR2021]  5320 non-null   object
 52  2022 [YR2022]  5320 non-null   object
 53  2023 [YR2023]  5320 non-null   object
dtypes: object(54)
memory usage: 2.2+ MB

,Country Name,Country Code,Series Name,Series Code,1974 [YR1974],1975 [YR1975],1976 [YR1976],1977 [YR1977],1978 [YR1978],1979 [YR1979],...,2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023]
0,Viet Nam,VNM,GDP (constant 2015 US$),NY.GDP.MKTP.KD,..,..,..,..,..,..,...,223632762207.56,239258328381.741,255264731908.124,272980590259.187,293358610036.841,314947640805.601,323972192107.065,332245562394.77,359235578724.112,377364153384.169
1,Viet Nam,VNM,GDP (constant LCU),NY.GDP.MKTP.KN,..,..,..,..,..,..,...,3.45539213E+15,3.69682571E+15,3.94414368E+15,4.21787476E+15,4.5327394E+15,4.8663156E+15,5.00575565E+15,5.13358906E+15,5.55061691E+15,5.8307249477943E+15
2,Viet Nam,VNM,GDP (current LCU),NY.GDP.MKTP.CN,..,..,..,..,..,..,...,4.93703168E+15,5.19132373E+15,5.639401E+15,6.29390455E+15,7.00904213E+15,7.70720029E+15,8.04438573E+15,8.4874756E+15,9.54873767E+15,1.02218146941153E+16
3,Viet Nam,VNM,GDP (current US$),NY.GDP.MKTP.CD,..,..,..,..,..,..,...,233451469642.519,239258328381.741,257096001177.982,281353605986.903,310106478394.659,334365270496.667,346615738537.796,366474752771.009,410324028883.325,429716969043.572
4,Viet Nam,VNM,GDP deflator (base year varies by country),NY.GDP.DEFL.ZS,..,..,..,..,..,..,...,142.879056681767,140.426520946263,142.981631947039,149.219806374716,154.631482454076,158.37855419817,160.702724872318,165.332197431479,172.030205377658,175.309499001185

### **Life_Expectancy**

In [24]:
life = pd.read_csv('Data/Life_Expectancy/5564778c-2f63-4042-9e49-8ce9c9a3a87d_Data.csv') 

life.info()

life.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 537 entries, 0 to 536
Data columns (total 68 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Country Name   534 non-null    object
 1   Country Code   532 non-null    object
 2   Series Name    532 non-null    object
 3   Series Code    532 non-null    object
 4   2023 [YR2023]  532 non-null    object
 5   2022 [YR2022]  532 non-null    object
 6   2021 [YR2021]  532 non-null    object
 7   2020 [YR2020]  532 non-null    object
 8   2019 [YR2019]  532 non-null    object
 9   2018 [YR2018]  532 non-null    object
 10  2017 [YR2017]  532 non-null    object
 11  2016 [YR2016]  532 non-null    object
 12  2015 [YR2015]  532 non-null    object
 13  2014 [YR2014]  532 non-null    object
 14  2013 [YR2013]  532 non-null    object
 15  2012 [YR2012]  532 non-null    object
 16  2011 [YR2011]  532 non-null    object
 17  2010 [YR2010]  532 non-null    object
 18  2009 [YR2009]  532 non-null    object
 19  2008 [YR2008]  532 non-null    object
 20  2007 [YR2007]  532 non-null    object
 21  2006 [YR2006]  532 non-null    object
 22  2005 [YR2005]  532 non-null    object
 23  2004 [YR2004]  532 non-null    object
 24  2003 [YR2003]  532 non-null    object
 25  2002 [YR2002]  532 non-null    object
 26  2001 [YR2001]  532 non-null    object
 27  2000 [YR2000]  532 non-null    object
 28  1999 [YR1999]  532 non-null    object
 29  1998 [YR1998]  532 non-null    object
 30  1997 [YR1997]  532 non-null    object
 31  1996 [YR1996]  532 non-null    object
 32  1995 [YR1995]  532 non-null    object
 33  1994 [YR1994]  532 non-null    object
 34  1993 [YR1993]  532 non-null    object
 35  1992 [YR1992]  532 non-null    object
 36  1991 [YR1991]  532 non-null    object
 37  1990 [YR1990]  532 non-null    object
 38  1989 [YR1989]  532 non-null    object
 39  1988 [YR1988]  532 non-null    object
 40  1987 [YR1987]  532 non-null    object
 41  1986 [YR1986]  532 non-null    object
 42  1985 [YR1985]  532 non-null    object
 43  1984 [YR1984]  532 non-null    object
 44  1983 [YR1983]  532 non-null    object
 45  1982 [YR1982]  532 non-null    object
 46  1981 [YR1981]  532 non-null    object
 47  1980 [YR1980]  532 non-null    object
 48  1979 [YR1979]  532 non-null    object
 49  1978 [YR1978]  532 non-null    object
 50  1977 [YR1977]  532 non-null    object
 51  1976 [YR1976]  532 non-null    object
 52  1975 [YR1975]  532 non-null    object
 53  1974 [YR1974]  532 non-null    object
 54  1973 [YR1973]  532 non-null    object
 55  1972 [YR1972]  532 non-null    object
 56  1971 [YR1971]  532 non-null    object
 57  1970 [YR1970]  532 non-null    object
 58  1969 [YR1969]  532 non-null    object
 59  1968 [YR1968]  532 non-null    object
 60  1967 [YR1967]  532 non-null    object
 61  1966 [YR1966]  532 non-null    object
 62  1965 [YR1965]  532 non-null    object
 63  1964 [YR1964]  532 non-null    object
 64  1963 [YR1963]  532 non-null    object
 65  1962 [YR1962]  532 non-null    object
 66  1961 [YR1961]  532 non-null    object
 67  1960 [YR1960]  532 non-null    object
dtypes: object(68)
memory usage: 285.4+ KB

,Country Name,Country Code,Series Name,Series Code,2023 [YR2023],2022 [YR2022],2021 [YR2021],2020 [YR2020],2019 [YR2019],2018 [YR2018],...,1969 [YR1969],1968 [YR1968],1967 [YR1967],1966 [YR1966],1965 [YR1965],1964 [YR1964],1963 [YR1963],1962 [YR1962],1961 [YR1961],1960 [YR1960]
0,Afghanistan,AFG,Young people (ages 15-24) newly infected with HIV,SH.HIV.INCD.YG,..,500,500,500,500,500,...,..,..,..,..,..,..,..,..,..,..
1,Afghanistan,AFG,Women's share of population ages 15+ living wi...,SH.DYN.AIDS.FE.ZS,..,29.3134328358209,29.2310408757835,29.1522648717482,29.0687880205896,28.9957430340557,...,..,..,..,..,..,..,..,..,..,..
2,Albania,ALB,Young people (ages 15-24) newly infected with HIV,SH.HIV.INCD.YG,..,100,100,100,100,100,...,..,..,..,..,..,..,..,..,..,..
3,Albania,ALB,Women's share of population ages 15+ living wi...,SH.DYN.AIDS.FE.ZS,..,28.7972508591065,28.5613540197461,28.3333333333333,28.1133482475764,27.9320987654321,...,..,..,..,..,..,..,..,..,..,..
4,Algeria,DZA,Young people (ages 15-24) newly infected with HIV,SH.HIV.INCD.YG,..,500,500,500,500,500,...,..,..,..,..,..,..,..,..,..,..

### **Giá trị Null**

**Nhận thấy một số lượng lớn dữ liệu bị thiếu nên em sẽ tiến hành kiểm tra phần trăm dữ liệu bị thiếu để tìm ra hướng xử lý như là xóa hết hay thay thế bằng giá trị trung bình, ...**

In [25]:
print(dr.isnull().sum())
print(dr.isnull().mean()*100)

Country Name       3
Country Code       5
Series Name        5
Series Code        5
1974 [YR1974]     15
1975 [YR1975]     15
1976 [YR1976]     15
1977 [YR1977]     14
1978 [YR1978]     14
1979 [YR1979]     14
1980 [YR1980]     14
1981 [YR1981]     15
1982 [YR1982]     15
1983 [YR1983]     15
1984 [YR1984]     14
1985 [YR1985]     14
1986 [YR1986]     14
1987 [YR1987]     14
1988 [YR1988]     14
1989 [YR1989]     13
1990 [YR1990]     11
1991 [YR1991]     11
1992 [YR1992]     11
1993 [YR1993]     11
1994 [YR1994]     11
1995 [YR1995]     11
1996 [YR1996]     11
1997 [YR1997]     12
1998 [YR1998]     12
1999 [YR1999]     12
2000 [YR2000]     11
2001 [YR2001]     11
2002 [YR2002]     11
2003 [YR2003]     11
2004 [YR2004]      8
2005 [YR2005]      9
2006 [YR2006]      8
2007 [YR2007]      9
2008 [YR2008]      9
2009 [YR2009]      9
2010 [YR2010]      9
2011 [YR2011]     10
2012 [YR2012]      9
2013 [YR2013]     10
2014 [YR2014]      8
2015 [YR2015]      9
2016 [YR2016]      8
2017 [YR2017]      9
2018 [YR2018]      8
2019 [YR2019]      8
2020 [YR2020]      9
2021 [YR2021]     10
2022 [YR2022]      8
2023 [YR2023]    271
dtype: int64
Country Name       1.107011
Country Code       1.845018
Series Name        1.845018
Series Code        1.845018
1974 [YR1974]      5.535055
1975 [YR1975]      5.535055
1976 [YR1976]      5.535055
1977 [YR1977]      5.166052
1978 [YR1978]      5.166052
1979 [YR1979]      5.166052
1980 [YR1980]      5.166052
1981 [YR1981]      5.535055
1982 [YR1982]      5.535055
1983 [YR1983]      5.535055
1984 [YR1984]      5.166052
1985 [YR1985]      5.166052
1986 [YR1986]      5.166052
1987 [YR1987]      5.166052
1988 [YR1988]      5.166052
1989 [YR1989]      4.797048
1990 [YR1990]      4.059041
1991 [YR1991]      4.059041
1992 [YR1992]      4.059041
1993 [YR1993]      4.059041
1994 [YR1994]      4.059041
1995 [YR1995]      4.059041
1996 [YR1996]      4.059041
1997 [YR1997]      4.428044
1998 [YR1998]      4.428044
1999 [YR1999]      4.428044
2000 [YR2000]      4.059041
2001 [YR2001]      4.059041
2002 [YR2002]      4.059041
2003 [YR2003]      4.059041
2004 [YR2004]      2.952030
2005 [YR2005]      3.321033
2006 [YR2006]      2.952030
2007 [YR2007]      3.321033
2008 [YR2008]      3.321033
2009 [YR2009]      3.321033
2010 [YR2010]      3.321033
2011 [YR2011]      3.690037
2012 [YR2012]      3.321033
2013 [YR2013]      3.690037
2014 [YR2014]      2.952030
2015 [YR2015]      3.321033
2016 [YR2016]      2.952030
2017 [YR2017]      3.321033
2018 [YR2018]      2.952030
2019 [YR2019]      2.952030
2020 [YR2020]      3.321033
2021 [YR2021]      3.690037
2022 [YR2022]      2.952030
2023 [YR2023]    100.000000
dtype: float64

In [26]:
dr["2023 [YR2023]"] = dr["2022 [YR2022]"]  # Sao chép giá trị năm 2022
dr.interpolate(method="linear", inplace=True)
dr.ffill(inplace=True)  # Điền dữ liệu còn thiếu từ trước
dr.bfill(inplace=True)  # Điền dữ liệu còn thiếu từ sau

C:\Users\ASUS\AppData\Local\Temp\ipykernel_16960\1364755925.py:2: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  dr.interpolate(method="linear", inplace=True)

In [28]:
print(dr.isnull().sum())

dr.head()

Country Name     0
Country Code     0
Series Name      0
Series Code      0
1974 [YR1974]    0
1975 [YR1975]    0
1976 [YR1976]    0
1977 [YR1977]    0
1978 [YR1978]    0
1979 [YR1979]    0
1980 [YR1980]    0
1981 [YR1981]    0
1982 [YR1982]    0
1983 [YR1983]    0
1984 [YR1984]    0
1985 [YR1985]    0
1986 [YR1986]    0
1987 [YR1987]    0
1988 [YR1988]    0
1989 [YR1989]    0
1990 [YR1990]    0
1991 [YR1991]    0
1992 [YR1992]    0
1993 [YR1993]    0
1994 [YR1994]    0
1995 [YR1995]    0
1996 [YR1996]    0
1997 [YR1997]    0
1998 [YR1998]    0
1999 [YR1999]    0
2000 [YR2000]    0
2001 [YR2001]    0
2002 [YR2002]    0
2003 [YR2003]    0
2004 [YR2004]    0
2005 [YR2005]    0
2006 [YR2006]    0
2007 [YR2007]    0
2008 [YR2008]    0
2009 [YR2009]    0
2010 [YR2010]    0
2011 [YR2011]    0
2012 [YR2012]    0
2013 [YR2013]    0
2014 [YR2014]    0
2015 [YR2015]    0
2016 [YR2016]    0
2017 [YR2017]    0
2018 [YR2018]    0
2019 [YR2019]    0
2020 [YR2020]    0
2021 [YR2021]    0
2022 [YR2022]    0
2023 [YR2023]    0
dtype: int64

,Country Name,Country Code,Series Name,Series Code,1974 [YR1974],1975 [YR1975],1976 [YR1976],1977 [YR1977],1978 [YR1978],1979 [YR1979],...,2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023]
0,Viet Nam,VNM,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,13.000000,9.480000,8.649000,8.534,8.339000,8.157000,...,6.373,6.444,6.495,6.577,6.663,6.706,6.169,7.317000,6.831,6.831
1,Afghanistan,AFG,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,24.773000,24.241000,23.718000,23.179,23.875000,24.797000,...,7.395,7.331,7.077,7.027,6.981,6.791,7.113,7.344000,6.906,6.906
2,Albania,ALB,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,7.417000,7.137000,6.937000,6.711,6.595000,6.445000,...,7.868,7.947,8.035,8.150,8.308,8.480,10.785,11.325000,11.194,11.194
3,Algeria,DZA,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,18.903000,18.065000,17.495000,16.631,15.661000,14.615000,...,4.555,4.437,4.472,4.542,4.482,4.392,5.398,4.546000,4.329,4.329
4,American Samoa,ASM,"Death rate, crude (per 1,000 people)",SP.DYN.CDRT.IN,20.138667,19.671333,19.277333,18.611,17.849667,17.055333,...,4.200,5.900,4.386,5.100,4.441,4.146,5.600,5.700333,7.800,7.800